weavefox/libro

- apps/docs/.dumirc.ts
- apps/docs/docs/examples/terminal.md
- apps/docs/package.json
- apps/docs/src/terminal/app.ts
- apps/docs/src/terminal/index.less
- apps/docs/src/terminal/index.tsx
- packages/libro-terminal/package.json
- packages/libro-terminal/src/app.tsx
- packages/libro-terminal/src/connection.ts
- packages/libro-terminal/src/index.less
- packages/libro-terminal/src/manager.ts
- packages/libro-terminal/src/module.ts
- packages/libro-terminal/src/protocol.ts
- packages/libro-terminal/src/restapi.ts
- packages/libro-terminal/src/theme-service.ts
- packages/libro-terminal/src/view.tsx
接入jupyter server 的terminal功能，提供测试界面如下
> feat: add terminal

- .changeset/tasty-stingrays-jump.md
- packages/libro-cofine-editor/src/libro-e2-editor.ts
- packages/libro-core/src/components/dnd-cell-item-render.tsx
- packages/libro-jupyter/src/file/file-command.tsx
- packages/libro-jupyter/src/file/file-service.ts
- packages/libro-lab/src/layout/saveable-tab-view.tsx
1.fix(core): stop propagation when focus cell right toolbar
2.fix(lab): close the open tab when delete the file
> fix(lab): close the open tab when delete the file

- .changeset/lovely-crabs-serve.md
- packages/libro-cofine-editor-core/package.json
https://github.com/difizen/libro/blob/8461c3ba51d9861f25f3248c9703f0a5f17affc2/packages/libro-cofine-editor-core/src/default-worker-contribution.ts#L18-L21
This file was not included
> fix: fix missing dist in package.json

- .changeset/early-monkeys-judge.md
- .changeset/fair-turkeys-deliver.md
- apps/docs/.dumi/theme/layouts/DocLayout.less
- packages/libro-core/src/components/dnd-component/default-dnd-content.tsx
- packages/libro-core/src/components/dnd-component/dnd-list.tsx
- packages/libro-core/src/components/libro-virtualized-render.tsx
- packages/libro-core/src/index.less
- packages/libro-core/src/libro-model.ts
- packages/libro-core/src/libro-protocol.ts
- packages/libro-jupyter/src/widget/widget-render.tsx
- packages/libro-jupyter/src/widget/widget-rendermime-contribution.ts
- packages/libro-jupyter/src/widget/widget-view.tsx
- packages/libro-lab/src/index.less
* #185 Better support for the widget cleanup process.
* #261 Positioning issues in cell rendering
> feat: widget & core cell rendering

- packages/libro-app/src/index.less
- packages/libro-core/src/index.less
> fix: set markdown style #302

- .changeset/hot-points-remember.md
- packages/libro-ai-native/src/module.ts
- packages/libro-prompt-cell/src/module.ts
> feat(prompt): configurable prompt cell module

- apps/docs/.dumirc.ts
- apps/docs/dumi-plugin-html-addon.ts
- apps/docs/package.json
- packages/libro-markdown/package.json
> Fix GA script

- apps/docs/dumi-plugin-html-addon.ts
- packages/libro-terminal/src/theme-service.ts
> fix type annotation

- apps/docs/docs/updates/index.md
- apps/docs/docs/updates/update20241115.md
- apps/docs/docs/updates/update20241115.zh-CN.md
> docs: add updates

- apps/docs/docs/updates/index.md
- apps/docs/docs/updates/index.zh-CN.md
- apps/docs/dumi-plugin-deploy.ts
> [docs] Remove examples when build in vercel environment

- .github/workflows/welcome.yml
- CONTRIBUTING.md
- CONTRIBUTING_zh.md
- README_zh.md
> chore: update contributing doc&add welcome action

- .github/workflows/pr-label-status-dummy.yml
- .github/workflows/pr-label-status.yml
> chore: add pr label status action

- .github/workflows/pr-label-status.yml
> fix: use bot token in "pr-label-status.yml" workflow

- .github/workflows/discord-release.yml
> chore: add discord release action

- .github/workflows/pr-label-title-body.yml
> fix: pr label by title action

- README.md
- README_zh.md
> docs: update discord link

- .github/workflows/pr-label-title-body.yml
> fix: pr label action

- .changeset/wicked-forks-hug.md
- examples/libro_guide_book.ipynb
- packages/libro-markdown-cell/src/index.less
> fix: improve markdown pre style& add libro guide notebook

- README.md
- README_zh.md
> docs: update contact info on readme

- .github/labels.yml
- .github/workflows/pr-label-title-body.yml
> chore: manage labels

- .github/workflows/config/pr-label-file-paths.yml
- .github/workflows/pr-label-file-paths.yml
- README.md
- README_zh.md
> chore: pr label by file path action

- packages/libro-app/src/index.less
- packages/libro-core/src/index.less
> fix: improve markdown style

- .changeset/eleven-baboons-dream.md
> chore: add changeset

- packages/libro-core/src/components/dnd-component/virtualized-manager.ts
- packages/libro-core/src/virtualized-manager.ts
> fix: disable virtual scrolling temporarily

- packages/libro-lab/src/module.tsx
> chore: remove ai capability

- README.md
- README_en.md
> docs: update readme

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/documentation-related.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- .github/workflows/welcome.yml
> chore: update actions

- archive/opensumi-module-libro/package.json
- archive/opensumi-module-libro/src/browser/kernel-panel/collapse/kernel-collapse-content-item.tsx
- archive/opensumi-module-libro/src/browser/libro-keybind-contribution.ts
- archive/opensumi-module-libro/src/mana/editor/keybind-handler.ts
- archive/opensumi-module-libro/src/mana/editor/module.ts
> fix: update keybind  &  open file in kernel panel on opensumi libro

- archive/umi-plugin-mana/package.json
- archive/umi-plugin-mana/src/index.spec.ts
- archive/umi-plugin-mana/src/mana-runtime.ts
- packages/libro-app/src/app-file-command-contribution.tsx
- packages/libro-app/src/app-open-handler.ts
- packages/libro-app/src/app-view.tsx
- packages/libro-app/src/app-viewer.tsx
- packages/libro-app/src/module.ts
> chore: update references related to the umi plugin mana &libro app

- packages/libro-markdown/package.json
- packages/libro-markdown/src/markdown-render.ts
> feat(markdown): prevent potential xss attacks caused by markdown syntax

- packages/libro-core/src/cell/libro-cell-view.tsx
- packages/libro-core/src/cell/libro-edit-cell-view.tsx
- packages/libro-core/src/command/libro-command-contribution.ts
- packages/libro-core/src/libro-protocol.ts
- packages/libro-core/src/libro-service.ts
- packages/libro-core/src/libro-view-tracker.ts
- packages/libro-core/src/libro-view.tsx
- packages/libro-core/src/utils/index.ts
> feat: add fps tracker &  optimize tracker time

- packages/libro-core/src/libro-service.ts
- packages/libro-core/src/libro-view.tsx
- packages/libro-jupyter/src/libro-jupyter-view.tsx
> fix: notebook tracker time error& add cellCount for fpsTracker

- examples/large_output.ipynb
- packages/libro-core/src/libro-view.tsx
- packages/libro-core/src/output/output-protocol.ts
- packages/libro-lab/src/libro-lab-view.tsx
- packages/libro-lab/src/module.tsx
- packages/libro-output/src/stream-output/stream-output-model.tsx
- packages/libro-rendermime/src/components/index.less
- packages/libro-rendermime/src/components/text-render.tsx
- packages/libro-rendermime/src/renderers.ts
- packages/libro-rendermime/src/rendermime-protocol.ts
- packages/libro-rendermime/src/rendermime-registry.ts
> feat: support output render in a new tab

- archive/opensumi-module-libro/src/mana/editor/opensumi-editor.ts
- packages/libro-common/src/common/vscode-uri/utils.ts
- packages/libro-common/src/path.ts
- packages/libro-common/src/url.ts
- packages/libro-jupyter/src/libro-jupyter-model.ts
> feat: the editor settings in opensumi also works for libro

- packages/libro-code-cell/src/code-cell-view.tsx
> refactor: no editor mode use github css as hightlight
